config/routes.rb
CourseLocations::Application.routes.draw do

  resources :variables

  resources :locations
  match 'locations/:id/delete' => 'locations#destroy', :as => :delete_location

  resources :areas
  match 'areas/:id/delete' => 'areas#destroy', :as => :delete_area
  match '/areas/new/:id(.:format)' => 'areas#new', :as => :new_child_area

  resources :venues
  match 'venues/:id/delete' => 'venues#destroy', :as => :delete_venue
  match '/venues/new/:id(.:format)' => 'venues#new', :as => :new_child_venue

  resources :organisations
  match 'organisations/:id/delete' => 'organisations#destroy', :as => :delete_organisation
  match '/organisations/new/:id(.:format)' => 'organisations#new', :as => :new_child_organisation

  resources :location_tree

  devise_for :users, :path_names => { :sign_up => "register" }
  root :to => "locations#index"

end

app/models/organisation.rb
class Organisation <  Area
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
  # GET /organisations
  # GET /organisations.xml
  def index
    @organisations = Organisation.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @organisations }
    end
  end

  # GET /organisations/1
  # GET /organisations/1.xml
  def show
    @organisation = Organisation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @organisation }
    end
  end

  # GET /organisations/new
  # GET /organisations/new.xml
  def new
    @organisation = Organisation.new
    @organisation.parent_id = params[:id] # needs to be kept by view in hidden field to get it to the create action

    respond_to do |format|
      if @organisation.parent.may_have_children?
        unless @organisation.parent.has_organisation_ancestor?
          format.html # new.html.haml
        else
          format.html { redirect_to(locations_url, :notice => "#{@organisation.parent.to_s} is already under an organisation.") }
        end
      else
        format.html { redirect_to(locations_url, :notice => "#{@organisation.parent.to_s} cannot have children.") }
      end
      format.xml  { render :xml => @organisation }
    end

  end

  # GET /organisations/1/edit
  def edit
    @organisation = Organisation.find(params[:id])
  end

  # POST /organisations
  # POST /organisations.xml
  def create
    @organisation = Organisation.new(params[:organisation])

    respond_to do |format|
      if @organisation.save
        format.html { redirect_to(locations_url, :notice => "#{@organisation.to_s} was successfully created.") }
        format.xml  { render :xml => @organisation, :status => :created, :location => @organisation }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @organisation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /organisations/1
  # PUT /organisations/1.xml
  def update
    @organisation = Organisation.find(params[:id])

    respond_to do |format|
      if @organisation.update_attributes(params[:organisation])
        format.html { redirect_to(locations_url, :notice => "#{@organisation.to_s} was successfully updated.") }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @organisation.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @organisation = Organisation.find(params[:id])

    if @organisation.children.size == 0 and @organisation.name != "localhost"
      @organisation.destroy
      flash[:notice] = "Deleted #{@organisation.to_s}"
    else
      flash[:notice] = "#{@organisation.to_s} not deleted. It has children or is the localhost node."
    end

    respond_to do |format|
      format.html { redirect_to(locations_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/organisations_helper.rb
module OrganisationsHelper
end

app/views/organisations/_form.html.haml
= form_for(@organisation) do |f|
  - if @organisation.errors.any?
    #error_explanation
      %h2= #{pluralize(@organisation.errors.count, "error")} prohibited this organisation from being saved:
      %ul
        - @organisation.errors.full_messages.each do |msg|
          %li= msg

  = f.hidden_field :parent_id
  %p
    %label.field Name
    = f.text_field :name

  %p
    =@organisation.parent_id
  %p
    Parent id: #{params[:id]}

  .actions
    = f.submit

app/views/organisations/edit.html.haml
%h1 Editing organisation

= render 'form'

= link_to 'Show', @organisation |
= link_to 'Back', locations_path

app/views/organisations/index.html.erb
<h1>Listing organisations</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @organisations.each do |organisation| %>
  <tr>
    <td><%= link_to 'Show', organisation %></td>
    <td><%= link_to 'Edit', edit_organisation_path(organisation) %></td>
    <td><%= link_to 'Destroy', organisation, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Organisation', new_organisation_path %>

app/views/organisations/new.html.haml
%h1 New organisation
%p
  = render 'form'
%p
  = link_to 'Back', locations_path

app/views/organisations/show.html.haml
%h1 New organisation
%p
  = render 'form'
%p
  = link_to 'Back', locations_path