config/routes.rb
CourseLocations::Application.routes.draw do

  resources :variables

  resources :locations
  match 'locations/:id/delete' => 'locations#destroy', :as => :delete_location

  resources :areas
  match 'areas/:id/delete' => 'areas#destroy', :as => :delete_area
  match '/areas/new/:id(.:format)' => 'areas#new', :as => :new_child_area

  resources :venues
  match 'venues/:id/delete' => 'venues#destroy', :as => :delete_venue
  match '/venues/new/:id(.:format)' => 'venues#new', :as => :new_child_venue

  resources :organisations
  match 'organisations/:id/delete' => 'organisations#destroy', :as => :delete_organisation
  match '/organisations/new/:id(.:format)' => 'organisations#new', :as => :new_child_organisation

  resources :location_tree

  devise_for :users, :path_names => { :sign_up => "register" }
  root :to => "locations#index"

end

app/controllers/location_tree_controller.rb
class LocationTreeController < ApplicationController
  def show
    #the menu action displays menu to ask user to add remove edit display a location
    @location = Location.find(params[:id])
  end

end

app/helpers/location_tree_helper.rb
module LocationTreeHelper
end

app/views/location_tree/show.html.haml
%h3= "Choose action on: #{@location.to_s}"
-# %p Parent Id: #{@location.parent_id}, Id: #{@location.id}

= stylesheet_link_tag 'appstylesheet'

%h5 Modify this node
%ul
  %li= button_to "Edit #{@location.to_s}", edit_location_path(@location), :method => :get
  %li= button_to "Delete #{@location.to_s}", location_path(@location), :method => :delete, :confirm => "Are you sure?", :title => "Confirm"

%h5 add a child (if it is not a venue)
%ul
  %li= button_to "Add an Area", new_child_area_path(@location), :method => :get
  %li= button_to "Add a Venue", new_child_venue_path(@location), :method => :get
  %li= button_to "Add an Organisation",new_child_organisation_path(@location), :method => :get

<p>
<a href="/locations"> Back </a>
-# %h5 params #{params}