config/routes.rb
CourseLocations::Application.routes.draw do

  resources :variables

  resources :locations
  match 'locations/:id/delete' => 'locations#destroy', :as => :delete_location

  resources :areas
  match 'areas/:id/delete' => 'areas#destroy', :as => :delete_area
  match '/areas/new/:id(.:format)' => 'areas#new', :as => :new_child_area

  resources :venues
  match 'venues/:id/delete' => 'venues#destroy', :as => :delete_venue
  match '/venues/new/:id(.:format)' => 'venues#new', :as => :new_child_venue

  resources :organisations
  match 'organisations/:id/delete' => 'organisations#destroy', :as => :delete_organisation
  match '/organisations/new/:id(.:format)' => 'organisations#new', :as => :new_child_organisation

  resources :location_tree

  devise_for :users, :path_names => { :sign_up => "register" }
  root :to => "locations#index"

end

app/models/variable.rb
class Variable < ActiveRecord::Base
end

app/controllers/variables_controller.rb
class VariablesController < ApplicationController
  # GET /variables
  # GET /variables.xml
  def index
    @variables = Variable.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @variables }
    end
  end

  # GET /variables/1
  # GET /variables/1.xml
  def show
    @variable = Variable.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @variable }
    end
  end

  # GET /variables/new
  # GET /variables/new.xml
  def new
    @variable = Variable.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @variable }
    end
  end

  # GET /variables/1/edit
  def edit
    @variable = Variable.find(params[:id])
  end

  # POST /variables
  # POST /variables.xml
  def create
    @variable = Variable.new(params[:variable])

    respond_to do |format|
      if @variable.save
        format.html { redirect_to(@variable, :notice => 'Variable was successfully created.') }
        format.xml  { render :xml => @variable, :status => :created, :location => @variable }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @variable.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /variables/1
  # PUT /variables/1.xml
  def update
    @variable = Variable.find(params[:id])

    respond_to do |format|
      if @variable.update_attributes(params[:variable])
        format.html { redirect_to(@variable, :notice => 'Variable was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @variable.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /variables/1
  # DELETE /variables/1.xml
  def destroy
    @variable = Variable.find(params[:id])
    @variable.destroy

    respond_to do |format|
      format.html { redirect_to(variables_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/variables_helper.rb
module VariablesHelper
end

app/views/variables/_form.html.erb
<%= form_for(@variable) do |f| %>
  <% if @variable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@variable.errors.count, "error") %> prohibited this variable from being saved:</h2>

      <ul>
      <% @variable.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/variables/edit.html.erb
<h1>Editing variable</h1>

<%= render 'form' %>

<%= link_to 'Show', @variable %> |
<%= link_to 'Back', variables_path %>

app/views/variables/index.html.erb
<h1>Listing variables</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @variables.each do |variable| %>
  <tr>
    <td><%= variable.name %></td>
    <td><%= variable.value %></td>
    <td><%= link_to 'Show', variable %></td>
    <td><%= link_to 'Edit', edit_variable_path(variable) %></td>
    <td><%= link_to 'Destroy', variable, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Variable', new_variable_path %>

app/views/variables/new.html.erb
<h1>New variable</h1>

<%= render 'form' %>

<%= link_to 'Back', variables_path %>

app/views/variables/show.html.erb
<p>
  <b>Name:</b>
  <%= @variable.name %>
</p>

<p>
  <b>Value:</b>
  <%= @variable.value %>
</p>


<%= link_to 'Edit', edit_variable_path(@variable) %> |
<%= link_to 'Back', variables_path %>